import type { components } from "@/lib/api/schema";

export type Product = components["schemas"]["Product"];

/** Seed catalog aligned to OpenAPI Product schema — used when API is unavailable. */
export const seedProducts: Product[] = [
  {
    id: "prod_house_blend",
    slug: "house-blend",
    name: "House Blend",
    description: "Chocolate, almond, and a clean citrus finish — roasted weekly in small batches.",
    priceCents: 1800,
    currency: "USD",
    category: "beans",
    imageUrl:
      "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=800&q=80",
    roastLevel: "medium",
    origin: "Colombia & Ethiopia",
    inStock: true,
    rating: 4.8,
    reviewCount: 214,
  },
  {
    id: "prod_single_origin",
    slug: "yirgacheffe-single",
    name: "Yirgacheffe Single Origin",
    description: "Jasmine, bergamot, and honey — washed process from high-altitude smallholders.",
    priceCents: 2200,
    currency: "USD",
    category: "beans",
    imageUrl:
      "https://images.unsplash.com/photo-1514432324607-09a9a8e2d2c8?auto=format&fit=crop&w=800&q=80",
    roastLevel: "light",
    origin: "Ethiopia",
    inStock: true,
    rating: 4.9,
    reviewCount: 156,
  },
  {
    id: "prod_espresso",
    slug: "midnight-espresso",
    name: "Midnight Espresso",
    description: "Dense crema, caramelized sugar, and dark cocoa — built for 9-bar extraction.",
    priceCents: 1900,
    currency: "USD",
    category: "beans",
    imageUrl:
      "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=800&q=80",
    roastLevel: "dark",
    origin: "Brazil & Guatemala",
    inStock: true,
    rating: 4.7,
    reviewCount: 98,
  },
  {
    id: "prod_chemex",
    slug: "glass-pour-over-set",
    name: "Glass Pour-Over Set",
    description: "Hand-blown carafe, filters, and a precision gooseneck companion guide.",
    priceCents: 6800,
    currency: "USD",
    category: "equipment",
    imageUrl:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80",
    roastLevel: "medium",
    origin: "Designed in Portland",
    inStock: true,
    rating: 4.6,
    reviewCount: 42,
  },
  {
    id: "prod_grinder",
    slug: "burr-grinder-pro",
    name: "Burr Grinder Pro",
    description: "40-step adjustment, low retention, and a quiet morning routine.",
    priceCents: 24900,
    currency: "USD",
    category: "equipment",
    imageUrl:
      "https://images.unsplash.com/photo-1517668808822-9ebb02b2a0e7?auto=format&fit=crop&w=800&q=80",
    roastLevel: "medium",
    origin: "Engineered in Seattle",
    inStock: true,
    rating: 4.8,
    reviewCount: 67,
  },
  {
    id: "prod_gift",
    slug: "tasting-flight-gift",
    name: "Tasting Flight Gift Box",
    description: "Three 8oz single origins with cupping notes and brew cards.",
    priceCents: 5400,
    currency: "USD",
    category: "gifts",
    imageUrl:
      "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=800&q=80",
    roastLevel: "medium",
    origin: "Rotating origins",
    inStock: true,
    rating: 4.9,
    reviewCount: 88,
  },
  {
    id: "prod_sub",
    slug: "monthly-roasters-pick",
    name: "Monthly Roaster's Pick",
    description: "A fresh 12oz bag shipped on the first of each month — pause anytime.",
    priceCents: 2000,
    currency: "USD",
    category: "subscriptions",
    imageUrl:
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80",
    roastLevel: "medium-dark",
    origin: "Seasonal selection",
    inStock: true,
    rating: 4.8,
    reviewCount: 301,
  },
  {
    id: "prod_decaf",
    slug: "swiss-water-decaf",
    name: "Swiss Water Decaf",
    description: "Full-bodied without caffeine — sugar cane sweetness and soft apple acidity.",
    priceCents: 2000,
    currency: "USD",
    category: "beans",
    imageUrl:
      "https://images.unsplash.com/photo-1559496417-e7f25cb247f3?auto=format&fit=crop&w=800&q=80",
    roastLevel: "medium",
    origin: "Peru",
    inStock: true,
    rating: 4.5,
    reviewCount: 73,
  },
];
